version: '2.2'
services:
  rancher:
    image: rancher/rancher:v2.4.4
    container_name: rancher
    volumes:
      - rancher-data:/var/lib/rancher
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
volumes:
  rancher-data: {}
