
apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: golang-helloworld-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-helloworld-app
spec:
  selector:
    matchLabels:
      app: golang-helloworld-app
  replicas: 5
  template:
    metadata:
      labels:
        app: golang-helloworld-app
    spec:
      containers:
      - name: golang-helloworld-app
        image: hello-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000